//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListIt_DataAccessModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiProduct
    {
        public int Id { get; set; }
        public int Currency_Id { get; set; }
        public Nullable<int> DefaultProduct_Id { get; set; }
        public int ShopApi_Id { get; set; }
        public int Unit_Id { get; set; }
        public string Endpoint { get; set; }
        public int Quantity { get; set; }
        public decimal? Price { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual DefaultProduct DefaultProduct { get; set; }
        public virtual Product Product { get; set; }
        public virtual ShopApi ShopApi { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
