//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListIt_DataAccessModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefaultProduct()
        {
            this.ApiProducts = new HashSet<ApiProduct>();
            this.LinkDefaultProductToCategories = new HashSet<LinkDefaultProductToCategory>();
            this.LinkUserToDefaultProducts = new HashSet<LinkUserToDefaultProduct>();
        }
    
        public int Id { get; set; }
        public int Currency_Id { get; set; }
        public int UnitType_Id { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Product_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiProduct> ApiProducts { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
        public virtual UnitType UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkDefaultProductToCategory> LinkDefaultProductToCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkUserToDefaultProduct> LinkUserToDefaultProducts { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
