//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListIt_DataAccessModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateSortedProduct
    {
        public int TemplateListOrderingId { get; set; }
        public int ProductId { get; set; }
        public int Rank { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TemplateListOrdering TemplateListOrdering { get; set; }
    }
}
