//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListIt_DataAccessModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProduct
    {
        public int Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Currency_Id { get; set; }
        public Nullable<int> UnitType_Id { get; set; }
        public int User_Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual User User { get; set; }
    }
}
