//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListIt_DataAccessModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntrySorting
    {
        public Nullable<int> NextEntryId_Id { get; set; }
        public Nullable<int> PrevEntryId_Id { get; set; }
        public int ShoppingListEntry_Id { get; set; }
        public int UserListSorting_Id { get; set; }
    
        public virtual ShoppingListEntry ShoppingListEntry { get; set; }
        public virtual ShoppingListEntry ShoppingListEntry1 { get; set; }
        public virtual ShoppingListEntry ShoppingListEntry2 { get; set; }
        public virtual UserListSorting UserListSorting { get; set; }
    }
}
