//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListIt_DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ListIt_DomainModel;
    
    public partial class dmaj0918_1074524Entities : DbContext
    {
        public dmaj0918_1074524Entities() : base("name=dmaj0918_1074524Entities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TranslationOfCategory>()
                .HasKey<int>(x => x.Category_Id)
                .HasKey<int>(x => x.Language_Id);

            modelBuilder.Entity<TranslationOfProduct>()
                .HasKey<int>(x => x.Language_Id)
                .HasKey<int>(x => x.Product_Id);

            modelBuilder.Entity<TranslationOfUnitType>()
                .HasKey<int>(x => x.Language_Id)
                .HasKey<int>(x => x.UnitType_Id);

            modelBuilder.Entity<UserEntrySorting>()
                .HasKey<int>(x => x.ShoppingListEntry_Id)
                .HasKey<int>(x => x.UserListSorting_Id);

            modelBuilder.Entity<TemplateSortedProduct>()
                .HasKey<int>(x => x.ProductId)
                .HasKey<int>(x => x.TemplateListOrderingId);

            modelBuilder.Entity<LinkUserToDefaultProduct>()
                .HasKey<int>(x => x.DefaultProductId)
                .HasKey<int>(x => x.UserId);

            modelBuilder.Entity<LinkUserToList>()
                .HasKey<int>(x => x.ShoppingListId)
                .HasKey<int>(x => x.UserId);

            modelBuilder.Entity<ApiProduct>()
                .HasRequired(x => x.Product)
                .WithRequiredDependent();

            modelBuilder.Entity<DefaultProduct>()
                .HasRequired(x => x.Product)
                .WithRequiredDependent();

            modelBuilder.Entity<UserProduct>()
                .HasRequired(x => x.Product)
                .WithRequiredDependent();

            modelBuilder.Entity<LinkUserToList>()
                .HasRequired(x => x.ListAccessType)
                .WithRequiredDependent();

            modelBuilder.Entity<Chain>()
                .HasOptional<ShopApi>(chain => chain.ShopApi)
                .WithMany()
                .WillCascadeOnDelete(true);
        }


    
        public virtual DbSet<ApiProduct> ApiProducts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Chain> Chains { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DefaultProduct> DefaultProducts { get; set; }
        public virtual DbSet<EntryState> EntryStates { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LinkUserToDefaultProduct> LinkUserToDefaultProducts { get; set; }
        public virtual DbSet<LinkUserToList> LinkUserToLists { get; set; }
        public virtual DbSet<ListAccessType> ListAccessTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ShopApi> ShopApis { get; set; }
        public virtual DbSet<ShoppingListEntry> ShoppingListEntries { get; set; }
        public virtual DbSet<ShoppingList> ShoppingLists { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<TemplateListOrdering> TemplateListOrderings { get; set; }
        public virtual DbSet<TemplateSortedProduct> TemplateSortedProducts { get; set; }
        public virtual DbSet<TranslationOfCategory> TranslationOfCategories { get; set; }
        public virtual DbSet<TranslationOfProduct> TranslationOfProducts { get; set; }
        public virtual DbSet<TranslationOfUnitType> TranslationOfUnitTypes { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<UserEntrySorting> UserEntrySortings { get; set; }
        public virtual DbSet<UserListSorting> UserListSortings { get; set; }
        public virtual DbSet<UserProduct> UserProducts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
