//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListIt_DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingListEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingListEntry()
        {
            this.UserEntrySortings = new HashSet<UserEntrySorting>();
            this.UserEntrySortings1 = new HashSet<UserEntrySorting>();
            this.UserEntrySortings2 = new HashSet<UserEntrySorting>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Product_Id { get; set; }
        public int ShoppingList_Id { get; set; }
        public int State_Id { get; set; }
    
        public virtual EntryState EntryState { get; set; }
        public virtual Product Product { get; set; }
        public virtual ShoppingList ShoppingList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEntrySorting> UserEntrySortings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEntrySorting> UserEntrySortings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEntrySorting> UserEntrySortings2 { get; set; }
    }
}
