//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListIt_DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationOfCategory
    {
        public int Category_Id { get; set; }
        public int Language_Id { get; set; }
        public string Translation { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
    }
}
